### ISSUE TITLE
Add ConflictsWith to mod.json

### ISSUE THREAD

**Issue by Dragon-32** [m22spencer/BattletechPerformanceFix#44]
Reading the change log, v2.6 of BattletechPerformanceFix incorporates the functionality of JustDieAlready

So, wouldn't adding this to BattletechPerformanceFix's mod.json be appropriate?
`"ConflictsWith": [ "JustDieAlready" ],`

**Comment by m22spencer** [comment]
The patch should be okay even if used alongside JustDieAlready, so this is probably fine for BattleTech 1.3.2.

BattleTech 1.4 update integrated JustDieAlready, so it is removed from bfix in latest release.

Since everyone is currently working towards 1.4 compatibility, going to just leave this as is.

Thanks for the report.
